languageCode = "en-us"
title = "Data Diluvium"
baseurl = "http://datadiluvium.com/"


name = "Data Diluvium"
license = "Apache-2.0"
licenselink = "https://github.com/Adron/datadiluvium/blob/master/LICENSE"
homepage = "http://datadiluvium.com"
tags = ["data", "deluge", "diluvium", "generator", "random"]
features = ["social", "images" ]
min_version= 0.14

description = "Welcome to the Data Diluvium Project. This is a project about data, generating that data, and tools to utilize the data for testing and developing applications and services."

author_url = "http://blog.adron.me"
project_url = "http://datadiluvium.com"
project_documentation = "http://datadiluvium/docs"

github_project_name = "datadiluvium"
github_user_name = "Adron"

first_color="#f8f8f8"
first_border_color="#e7e7e7"
first_text_color="#333"

second_color="white"
second_text_color="#333"

header_color="#f8f8f8"
header_text_color="rgb(51, 51, 51)"

header_link_color="#777"
header_link_hover_color="rgb(51, 51, 51)"


[params]
    description = "Getting involved with data diluvium!"
    googleAnalytics = "UA-39158070-8"
[[params.social]]
    title = "email"
    icon = "envelope-o"
    url = "mailto:datadiluvium@thrashingcode.com"
[[params.social]]
    title = "twitter"
    icon = "twitter"
    url = "https://twitter.com/datadiluvium"
[[params.social]]
    title = "github"
    icon = "github"
    url = "https://github.com/Adron/datadiluvium"
